[package]
name = "api_types"
edition = "2021"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
quick-xml = { version = "0.36.2", features = ["serialize"] }
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
ron = "0.8.1"
