[alias]
make = ["bin", "cargo-make"]
nextest = ["bin", "cargo-nextest", "run", "--workspace"]
tauri = ["bin", "cargo-tauri"]
watch = ["bin", "cargo-watch"]
stylance = ["bin", "stylance", "."]
leptosfmt = ["bin", "leptosfmt", "./src/**/*.rs"]
trunk = ["bin", "trunk"]
